[package]
name = "Lucky13Prng"
version = "0.1.0"
edition = "2021"
rust-version = "1.82.0"

[dependencies]
bit_reverse = "0.1.8"
permutations = "0.1.1"
rand_core = "0.9.0-alpha.2"
rand = "0.9.0-alpha.2"